version: "3.8"

services:
  api:
    container_name: frizz_api
    restart: unless-stopped
    image: frizz_api:1.0
    build:
      context: server
      dockerfile: Dockerfile
      target: production
    ports:
      - 4000:4000
    networks:
      - shared-network

  client:
    container_name: frizz_client
    restart: unless-stopped
    image: frizz_client:1.0
    build:
      context: client
      dockerfile: Dockerfile
      target: production
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - shared-network
    stdin_open: true
    depends_on:
      - api

networks:
  shared-network:
